//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class BODYTYPEWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(BODYTYPE));
		L.RegVar("LoginData", get_LoginData, null);
		L.RegVar("LoginResponse", get_LoginResponse, null);
		L.RegVar("CharacterData", get_CharacterData, null);
		L.RegVar("LoginOut", get_LoginOut, null);
		L.RegVar("Frame", get_Frame, null);
		L.RegVar("GameState", get_GameState, null);
		L.RegVar("HashString", get_HashString, null);
		L.RegVar("UserMoney", get_UserMoney, null);
		L.RegVar("PlayerOptData", get_PlayerOptData, null);
		L.RegVar("PlayerMessage", get_PlayerMessage, null);
		L.RegVar("ServerInfo", get_ServerInfo, null);
		L.RegFunction("IntToEnum", IntToEnum);
		L.EndEnum();
		TypeTraits<BODYTYPE>.Check = CheckType;
		StackTraits<BODYTYPE>.Push = Push;
	}

	static void Push(IntPtr L, BODYTYPE arg)
	{
		ToLua.Push(L, arg);
	}

	static bool CheckType(IntPtr L, int pos)
	{
		return TypeChecker.CheckEnumType(typeof(BODYTYPE), L, pos);
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_LoginData(IntPtr L)
	{
		ToLua.Push(L, BODYTYPE.LoginData);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_LoginResponse(IntPtr L)
	{
		ToLua.Push(L, BODYTYPE.LoginResponse);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_CharacterData(IntPtr L)
	{
		ToLua.Push(L, BODYTYPE.CharacterData);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_LoginOut(IntPtr L)
	{
		ToLua.Push(L, BODYTYPE.LoginOut);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Frame(IntPtr L)
	{
		ToLua.Push(L, BODYTYPE.Frame);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_GameState(IntPtr L)
	{
		ToLua.Push(L, BODYTYPE.GameState);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_HashString(IntPtr L)
	{
		ToLua.Push(L, BODYTYPE.HashString);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_UserMoney(IntPtr L)
	{
		ToLua.Push(L, BODYTYPE.UserMoney);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_PlayerOptData(IntPtr L)
	{
		ToLua.Push(L, BODYTYPE.PlayerOptData);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_PlayerMessage(IntPtr L)
	{
		ToLua.Push(L, BODYTYPE.PlayerMessage);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ServerInfo(IntPtr L)
	{
		ToLua.Push(L, BODYTYPE.ServerInfo);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IntToEnum(IntPtr L)
	{
		int arg0 = (int)LuaDLL.lua_tonumber(L, 1);
		BODYTYPE o = (BODYTYPE)arg0;
		ToLua.Push(L, o);
		return 1;
	}
}

