//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class Net_PlayerOptDataWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(Net.PlayerOptData), typeof(System.Object));
		L.RegFunction("Clone", Clone);
		L.RegFunction("Equals", Equals);
		L.RegFunction("GetHashCode", GetHashCode);
		L.RegFunction("ToString", ToString);
		L.RegFunction("WriteTo", WriteTo);
		L.RegFunction("CalculateSize", CalculateSize);
		L.RegFunction("MergeFrom", MergeFrom);
		L.RegFunction("New", _CreateNet_PlayerOptData);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegConstant("OptFieldNumber", 1);
		L.RegConstant("UseridFieldNumber", 2);
		L.RegConstant("RoomidFieldNumber", 3);
		L.RegConstant("ItemidFieldNumber", 4);
		L.RegVar("Parser", get_Parser, null);
		L.RegVar("Descriptor", get_Descriptor, null);
		L.RegVar("Opt", get_Opt, set_Opt);
		L.RegVar("Userid", get_Userid, set_Userid);
		L.RegVar("Roomid", get_Roomid, set_Roomid);
		L.RegVar("Itemid", get_Itemid, set_Itemid);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateNet_PlayerOptData(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				Net.PlayerOptData obj = new Net.PlayerOptData();
				ToLua.PushSealed(L, obj);
				return 1;
			}
			else if (count == 1)
			{
				Net.PlayerOptData arg0 = (Net.PlayerOptData)ToLua.CheckObject(L, 1, typeof(Net.PlayerOptData));
				Net.PlayerOptData obj = new Net.PlayerOptData(arg0);
				ToLua.PushSealed(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: Net.PlayerOptData.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Clone(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Net.PlayerOptData obj = (Net.PlayerOptData)ToLua.CheckObject(L, 1, typeof(Net.PlayerOptData));
			Net.PlayerOptData o = obj.Clone();
			ToLua.PushSealed(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Equals(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 2 && TypeChecker.CheckTypes<Net.PlayerOptData>(L, 2))
			{
				Net.PlayerOptData obj = (Net.PlayerOptData)ToLua.CheckObject(L, 1, typeof(Net.PlayerOptData));
				Net.PlayerOptData arg0 = (Net.PlayerOptData)ToLua.ToObject(L, 2);
				bool o = obj != null ? obj.Equals(arg0) : arg0 == null;
				LuaDLL.lua_pushboolean(L, o);
				return 1;
			}
			else if (count == 2 && TypeChecker.CheckTypes<object>(L, 2))
			{
				Net.PlayerOptData obj = (Net.PlayerOptData)ToLua.CheckObject(L, 1, typeof(Net.PlayerOptData));
				object arg0 = ToLua.ToVarObject(L, 2);
				bool o = obj != null ? obj.Equals(arg0) : arg0 == null;
				LuaDLL.lua_pushboolean(L, o);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: Net.PlayerOptData.Equals");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetHashCode(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Net.PlayerOptData obj = (Net.PlayerOptData)ToLua.CheckObject(L, 1, typeof(Net.PlayerOptData));
			int o = obj.GetHashCode();
			LuaDLL.lua_pushinteger(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ToString(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Net.PlayerOptData obj = (Net.PlayerOptData)ToLua.CheckObject(L, 1, typeof(Net.PlayerOptData));
			string o = obj.ToString();
			LuaDLL.lua_pushstring(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int WriteTo(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Net.PlayerOptData obj = (Net.PlayerOptData)ToLua.CheckObject(L, 1, typeof(Net.PlayerOptData));
			Google.Protobuf.CodedOutputStream arg0 = (Google.Protobuf.CodedOutputStream)ToLua.CheckObject(L, 2, typeof(Google.Protobuf.CodedOutputStream));
			obj.WriteTo(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int CalculateSize(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Net.PlayerOptData obj = (Net.PlayerOptData)ToLua.CheckObject(L, 1, typeof(Net.PlayerOptData));
			int o = obj.CalculateSize();
			LuaDLL.lua_pushinteger(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int MergeFrom(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 2 && TypeChecker.CheckTypes<Net.PlayerOptData>(L, 2))
			{
				Net.PlayerOptData obj = (Net.PlayerOptData)ToLua.CheckObject(L, 1, typeof(Net.PlayerOptData));
				Net.PlayerOptData arg0 = (Net.PlayerOptData)ToLua.ToObject(L, 2);
				obj.MergeFrom(arg0);
				return 0;
			}
			else if (count == 2 && TypeChecker.CheckTypes<Google.Protobuf.CodedInputStream>(L, 2))
			{
				Net.PlayerOptData obj = (Net.PlayerOptData)ToLua.CheckObject(L, 1, typeof(Net.PlayerOptData));
				Google.Protobuf.CodedInputStream arg0 = (Google.Protobuf.CodedInputStream)ToLua.ToObject(L, 2);
				obj.MergeFrom(arg0);
				return 0;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: Net.PlayerOptData.MergeFrom");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Parser(IntPtr L)
	{
		try
		{
			ToLua.PushSealed(L, Net.PlayerOptData.Parser);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Descriptor(IntPtr L)
	{
		try
		{
			ToLua.PushSealed(L, Net.PlayerOptData.Descriptor);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Opt(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Net.PlayerOptData obj = (Net.PlayerOptData)o;
			Net.PlayerOpt ret = obj.Opt;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index Opt on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Userid(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Net.PlayerOptData obj = (Net.PlayerOptData)o;
			int ret = obj.Userid;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index Userid on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Roomid(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Net.PlayerOptData obj = (Net.PlayerOptData)o;
			int ret = obj.Roomid;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index Roomid on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Itemid(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Net.PlayerOptData obj = (Net.PlayerOptData)o;
			int ret = obj.Itemid;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index Itemid on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_Opt(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Net.PlayerOptData obj = (Net.PlayerOptData)o;
			Net.PlayerOpt arg0 = (Net.PlayerOpt)ToLua.CheckObject(L, 2, typeof(Net.PlayerOpt));
			obj.Opt = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index Opt on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_Userid(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Net.PlayerOptData obj = (Net.PlayerOptData)o;
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			obj.Userid = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index Userid on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_Roomid(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Net.PlayerOptData obj = (Net.PlayerOptData)o;
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			obj.Roomid = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index Roomid on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_Itemid(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Net.PlayerOptData obj = (Net.PlayerOptData)o;
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			obj.Itemid = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index Itemid on a nil value");
		}
	}
}

