//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class Net_LoginData_TypesWrap
{
	public static void Register(LuaState L)
	{
		L.BeginStaticLibs("Types");
		L.EndStaticLibs();
	}
}

